sudo: required
dist: trusty
language: node_js
node_js:
  - 10
before_install:
  - npm i npm@^6 -g
install:
  - npm install
script:
  - npm run build-ci
  - npm run test-ci
after_success:
  - npm run report-coverage
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
notifications:
  email: false
