sudo: required
dist: trusty
language: node_js
node_js:
  - 10
install:
  - npm ci
script:
  - npm run build:ci
  - npm run lint:ci
  - npm run validate-types:ci
  - npm run test:ci
after_success:
  - npm run report-coverage
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
notifications:
  on_success: change
  on_failure: always
